version: '3.8'

services:
  micro_examen:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8004"  # Mapea el puerto 8004 del contenedor al 8004 de tu máquina
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/examdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"  # Mapea el puerto 3306 del contenedor al 3306 de tu máquina
    environment:
      MYSQL_DATABASE: examdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
